### PR TITLE
Issue1844 move interpolate to math

### LINKED ISSUE #1844: Move Airflow.Multizone.BaseClasses.interpolate to Utilities.Math.Functions
First suggested in #1840.
This issue is to move the function `Airflow.Multizone.BaseClasses.interpolate` to `Utilities.Math.Functions` and to create a corresponding block under `Utilities.Math`.

### PR DESCRIPTION
**Pull request by hcasperfu**
This closes #1844.

### CODE REVIEW

**Comment by hcasperfu** [comment]
@mwetter -
The two moved classes did not exist yet at `v3.0.0`, and therefore the conversion script shouldn't apply here.

**Comment by mwetter** [comment]
> @mwetter - The two moved classes did not exist yet at `v3.0.0`, and therefore the conversion script shouldn't apply here.

Thanks for checking. (In `Buildings` we likely need to add the rename to the conversion script.)

**Comment by hcasperfu** [comment]
Can each library please review (or tag someone appropriate) and provide feedback by Friday March 22nd?
_AixLib_ @FWuellhorst 
_BuildingSystems_ @nytschgeusen 
_IDEAS_ @jelgerjansen

**Comment by FWuellhorst** [comment]
We don't use the function in AixLib, so it is fine for us.

**Comment by jelgerjansen** [comment]
I checked in the IDEAS library and double checked with Ghent University, but we also don't use the function in one of our library-specific models.

**Comment by nytschgeusen** [comment]
Also BuildingSystems doesn't use the interpolate function in its specific models ...

**Comment by hcasperfu** [comment]
Thank you for all your feedback!

@mwetter -
There is no objection from the libraries. This PR is ready to merge.

**Review by mwetter — APPROVED** [review]

**Pull request merged**
