### PR TITLE
Issue1139 broken links

### LINKED ISSUE #1139: Corrected broken hyperlinks in documentation
Following broken hyperlinks should be fixed. To reproduce this list, open the library and export the html documentation.
```
Error: Can not resolve link "IBPSA.Fluid.SolarCollectors" in IBPSA.BoundaryConditions.UsersGuide
Error: Can not resolve link "modelica://IBPSA.Fluid.Sources.FixedBoundary" in IBPSA.Fluid.UsersGuide
Error: Can not resolve link "modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC" in IBPSA.Fluid.FMI.ExportContainers.HVACZone
Error: Can not resolve link "modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC" in IBPSA.Fluid.FMI.ExportContainers.HVACZones
Error: Can not resolve link "modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC" in IBPSA.Fluid.FMI.ExportContainers.ThermalZone
Error: Can not resolve link "modelica://IBPSA.ThermalZones.Detailed" in IBPSA.Fluid.FMI.ExportContainers.ThermalZone
Error: Can not resolve link "modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC" in IBPSA.Fluid.FMI.ExportContainers.ThermalZone
Error: Can not resolve link "modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC" in IBPSA.Fluid.FMI.ExportContainers.ThermalZones
Error: Can not resolve link "modelica://IBPSA.ThermalZones.Detailed" in IBPSA.Fluid.FMI.ExportContainers.ThermalZones
Error: Can not resolve link "modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC" in IBPSA.Fluid.FMI.ExportContainers.ThermalZones
Error: Can not resolve link "modelica://IBPSA.Examples.Tutorial.SpaceCooling.System3" in IBPSA.Fluid.FMI.ExportContainers.Examples.FMUs.HVACZone
Error: Can not resolve link "modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC" in IBPSA.Fluid.FMI.ExportContainers.Examples.FMUs.HVACZone
Error: Can not resolve link "modelica://IBPSA.Examples.Tutorial.SpaceCooling.System3" in IBPSA.Fluid.FMI.ExportContainers.Examples.FMUs.ThermalZone
Error: Can not resolve link "modelica://IBPSA.Examples.Tutorial.SpaceCooling.System3" in IBPSA.Fluid.FMI.ExportContainers.Examples.FMUs.ThermalZones
Error: Can not resolve link "modelica://IBPSA.Fluid.PlugFlowPipes.BaseClasses.HeatLossPipeDelay" in IBPSA.Fluid.FixedResistances.BaseClasses.PlugFlowTransportDelay
Error: Can not resolve link "modelica://IBPSA.Fluid.PlugFlowPipes.BaseClasses.PipeCore" in IBPSA.Fluid.FixedResistances.BaseClasses.PlugFlowTransportDelay
Error: Can not resolve link "modelica://IBPSA.Fluid.HeatExchangers.Ground" in IBPSA.Fluid.Geothermal.Borefields.Data
Error: Can not resolve link "modelica://IBPSA.Fluid.HeatExchangers.Ground" in IBPSA.Fluid.Geothermal.Borefields.Data.Borefield
Error: Can not resolve link "modelica://IBPSA.Fluid.HeatExchangers.Ground" in IBPSA.Fluid.Geothermal.Borefields.Data.Configuration
Error: Can not resolve link "modelica://IBPSA.Fluid.HeatExchangers.Ground" in IBPSA.Fluid.Geothermal.Borefields.Data.Filling
Error: Can not resolve link "modelica://IBPSA.Fluid.HeatExchangers.Ground" in IBPSA.Fluid.Geothermal.Borefields.Data.Soil
Error: Can not resolve link "modelica://IBPSA.Fluid.HeatExchangers.Ground" in IBPSA.Fluid.Geothermal.Borefields.Examples
Error: Can not resolve link "modelica://IBPSA.Fluid.HeatExchangers.Ground" in IBPSA.Fluid.Geothermal.Borefields.Validation
Error: Can not resolve link "modelica://IBPSA.Fluid.HeatExchangers.Ground" in IBPSA.Fluid.Geothermal.Borefields.BaseClasses
Error: Can not resolve link "modelica://IBPSA.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.partialBorehole" in IBPSA.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.Examples.BaseClasses.PartialBorehole
Error: Can not resolve link "modelica://IBPSA.Fluid.HeatExchangers.Boreholes" in IBPSA.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses
Error: Can not resolve link "modelica://IBPSA.Fluid.Geothermal.Borefields.BaseClasses.ThermalResponseFactors.cylindricalHeatSource_Integrand" in IBPSA.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.cylindricalHeatSource
Error: Can not resolve link "modelica://IBPSA.Fluid.Sources.Outside_Cp" in IBPSA.Fluid.Sources.Outside_CpLowRise
Error: Can not resolve link "modelica://IBPSA.Fluid.Sources.FixedBoundary" in IBPSA.Fluid.Storage.ExpansionVessel
Error: Can not resolve link "modelica://IBPSA.Fluid.Sources.FixedBoundary" in IBPSA.Fluid.Storage.ExpansionVessel
Error: Can not resolve link "modelica://IBPSA.Fluid.Sources.FixedBoundary" in IBPSA.Fluid.Storage.ExpansionVessel
Error: Can not resolve link "modelica://Modelica.Fluid.HeatExchangers.BasicHX" in IBPSA.Fluid.Interfaces.EightPortHeatMassExchanger
Error: Can not resolve link "modelica://IBPSA.Media.Antifreeze.density_TX_a" in IBPSA.Media.Antifreeze.Validation.BaseClasses.PropyleneGlycolWater.testDensity_TX_a
Error: Can not resolve link "modelica://IBPSA.Media.Antifreeze.dynamicViscosity_TX_a" in IBPSA.Media.Antifreeze.Validation.BaseClasses.PropyleneGlycolWater.testDynamicViscosity_TX_a
Error: Can not resolve link "modelica://IBPSA.Media.Antifreeze.fusionTemperature_TX_a" in IBPSA.Media.Antifreeze.Validation.BaseClasses.PropyleneGlycolWater.testFusionTemperature_TX_a
Error: Can not resolve link "modelica://IBPSA.Media.Antifreeze.specificHeatCapacityCp_TX_a" in IBPSA.Media.Antifreeze.Validation.BaseClasses.PropyleneGlycolWater.testSpecificHeatCapacityCp_TX_a
Error: Can not resolve link "modelica://IBPSA.Media.Antifreeze.thermalConductivity_TX_a" in IBPSA.Media.Antifreeze.Validation.BaseClasses.PropyleneGlycolWater.testThermalConductivity_TX_a
Error: Can not resolve link "IBPSA.Fluid.SolarCollectors" in IBPSA.Types.Tilt
```

### PR DESCRIPTION
**Pull request by JayHuLBL**
This closes #1139.

- [x] fixed the broken hyperlinks caused by the classes refactoring

### CODE REVIEW

**Comment by JayHuLBL** [comment]
@mwetter The remaining broken link has been fixed. It's ready for review.

**Comment by mwetter** [comment]
@PMehrfeld : Can you please review and approve so that I can merge (we need one non-LBL approval)

**Comment by PMehrfeld** [comment]
@mwetter or @JayHuLBL : Could you please let me know me, which tool/script you used so that I can do a check by myself (although I do not expect to find any further broken link).

**Comment by JayHuLBL** [comment]
> @mwetter or @JayHuLBL : Could you please let me know me, which tool/script you used so that I can do a check by myself (although I do not expect to find any further broken link).

@PMehrfeld You can use Dymola, open the library and export the html documentation.

**Comment by mwetter** [comment]
Add conditional documentation in the form
```
<!-- @include_Buildings_1 -->
```
and replace the above string with text when merging it to the Buildings library in the merge script `mergeIBPSA.py`

**Comment by JayHuLBL** [comment]
@PMehrfeld Thanks for your review. The image and web links have been corrected. 

@PMehrfeld @mwetter For the internal links, since the links are necessary for Buildings library, I corrected the errors as below:
- original documentation:
```
The example
<a href=\"modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC\">
IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC</a>
shows how such an FMU can be connected
to an HVAC system that has signal flow.
```
- add conditional documentation:
```
<!--
@The example
<a href=\"modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC\">
IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC</a>
shows how such an FMU can be connected
to an HVAC system that has signal flow.
-->
```
In this way, it will not cause the hyperlink error when merging IBPSA library to other libraries. By replacing the string with text when merging it to Buildings library, the internal links will become valid.

**Comment by PMehrfeld** [comment]
@JayHuLBL : Thanks for the information. 

However, after adding conditional documentation in 21d6214 CI failed.

**Comment by mwetter** [comment]
@JayHuLBL How would you parse
```
<!--
@The example
<a href=\"modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC\">
IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC</a>
shows how such an FMU can be connected
to an HVAC system that has signal flow.
-->
```
when merging with the Buildings library only, but not with other libraries? Wouldn't it be easier to use
```
<!-- @include_Buildings
The example
<a href=\"modelica://IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC\">
IBPSA.Fluid.FMI.ExportContainers.Validation.RoomHVAC</a>
shows how such an FMU can be connected
to an HVAC system that has signal flow.
-->
```
as then we identify that this would be included in the Buildings library only. If say `AixLib` also likes to have snippet, one could enter 
```
<!-- @include_Buildings @include_AixLib
```

**Comment by JayHuLBL** [comment]
@mwetter The flag texts have been updated.

**Comment by mwetter** [comment]
This is ready to merge when all tests pass.

**Pull request merged**
