### PR TITLE
Issue725 c2flow functions

### PR DESCRIPTION
**Pull request by Mathadon**
this is for #725 

Due to the changed regularisation, some unit tests produced different results in many example. Most interestingly:

1)
`IBPSA.Fluid.Examples.FlowSystem.Simplified1` failed in my unit test run, but did run successfully outside of the unit tests.  Let's see what travis says..

2) A graphical illustration of how the flow curves change:
screen shot 2017-05-01 at 15 04 31
screen shot 2017-05-01 at 15 05 06

3) The unit test of `IBPSA.Fluid.Movers.Validation.PumpCurveDerivatives` produced very different results. The cause of this is that `res.m_flow` is orders of magnitude smaller than `res.m_flow_nominal` due to which the flow curve is far in the regularisation region. This leads to significantly different flow rates and therefore also to significantly different derivatives, as can be seen below:
screen shot 2017-05-01 at 15 12 53

### CODE REVIEW

**Comment by Mathadon** [comment]
@mwetter travis gets different results than I do. I'll get Dymola 2017FD01 to try and fix this.

**Comment by Mathadon** [comment]
@mwetter this is ready to be merged

**Comment by mwetter** [comment]
@Mathadon This is ready to merge if the tests pass. I corrected several html errors in https://github.com/ibpsa/modelica-ibpsa/pull/762/commits/8914ce1ed28809dad0cd04da0e9c9dadb50feace

**Comment by Mathadon** [comment]
@mwetter thanks, I wasn't aware that these were errors. I'll try to pay attention to them.

**Pull request merged**
