### PR TITLE
Issue1059 control io no socket

### PR DESCRIPTION
**Pull request by dhblum**
For https://github.com/ibpsa/modelica-ibpsa/issues/1059.

### CODE REVIEW

**Comment by dhblum** [comment]
FYI @JavierArroyoBastida, I've made this PR and asked for a review by @mwetter .

**Comment by dhblum** [comment]
@mwetter Thank you for completing your review.  I agree with all of your suggestions, except made one correction to revision documentation, which I've fixed in https://github.com/ibpsa/modelica-ibpsa/pull/1170/commits/efd933f25bc77300f23c449d7351b082f0c4cd75.

The change in parameter name to lower case is noted.  It will affect downstream tools, but should be fixed easily.  I've already added it as a to-do in the BOTEST repo at https://github.com/ibpsa/project1-boptest/issues/49.

**Comment by mwetter** [comment]
Thanks @dhblum . 
@PMehrfeld , this is ready for review and merging.

**Comment by mwetter** [comment]
@PMehrfeld : can you please review and merge if you agree with the implementation.

**Pull request merged**
