### PR TITLE
Issue944 heat pump

### LINKED ISSUE #944: merge Buildings heat pump model into IBPSA
I'd like to merge the Buildings heat pump model into IBPSA. @mlauster @thorade would there be an interest for this?

See also https://github.com/open-ideas/IDEAS/issues/731 for some more discussion.

### PR DESCRIPTION
**Pull request by Mathadon**
This closes #944

@mwetter I copied the python scripts but I did not yet test them. I presume that they are not included in the unit tests? Should they be included?

This is not yet ready to merge.

### CODE REVIEW

**Comment by Mathadon** [comment]
@mwetter do you have feedback on my question?

**Comment by mwetter** [comment]
@Mathadon Sorry, I forgot about this question. I added the tests for the Python files in ceeb53b

**Comment by Mathadon** [comment]
@mwetter thanks for adding the files. I still have to do a final check of the unit tests.

**Comment by Mathadon** [comment]
@mwetter I went ahead and updated the file in 262d4b0176b6879e594e7049f9dd2205a57b0219. Feel free to revert it if we need to check this further.

**Comment by Mathadon** [comment]
@mwetter this is ready to be merged

**Pull request merged**
