### PR TITLE
Update IBPSA Library to MSL 4.0.0

### LINKED ISSUE #1563: Update IBPSA Library to MSL 4.0.0
This issue is to update the IBPSA library to MSL 4.0.0.

The update is done with the Dymola conversion script.

Afterwards,
```bash
for ff in `find . -name '*.mo'`; do dos2unix $ff; done
```
is run to avoid changes like
```diff
within IBPSA.Fluid.FixedResistances.Validation.PlugFlowPipes.Data;
+<U+FEFF>within IBPSA.Fluid.FixedResistances.Validation.PlugFlowPipes.Data;
```

### PR DESCRIPTION
**Pull request by mwetter**
This closes #1563

### CODE REVIEW

**Comment by mwetter** [comment]
@Mathadon @cvering : Please review this non-backward compatible change. The ticket states how the library was updated. (So you don't have to look at each of the 604 files that changed.) If you agree, please report through the review feature, or add requested changes.

**Review by Mathadon — APPROVED** [review]
Exciting! Out of curiosity, are there other changes than the units conversion and `dos2unix`?

**Comment by mwetter** [comment]
@Mathadon : Calls to `Media` also changed slightly, but this is very localized. For most other models, including those in `Fluid`, simply replacing `SIunits` should suffice if you need to change models manually.

**Comment by mwetter** [comment]
@cvering : Can you please submit your review so we can merge this. The 2 week review period is close to being passed.

**Comment by mwetter** [comment]
Merged to master as the 2 week review period is over.

**Pull request merged**
