### PR TITLE
Correct volume model so it works with media from MSL that have no water and reducedX=false

### LINKED ISSUE #1650: Volume model not working with MSL mixture gasses
This issue to see how to possibly fix the issue reported in https://github.com/lbl-srg/modelica-buildings/issues/3132 as the root cause is not in Buildings but in IBPSA or in models used by IBPSA.

@justnielsen: This needs further investigation due to the failed function call to `setState_phX`.

### PR DESCRIPTION
**Pull request by mwetter**
This closes #1650

### CODE REVIEW

**Comment by justnielsen** [comment]
Thanks very much for the effort on this issue — it's highly appreciated!

A lot of the obstacles have been removed (in fan models etc.) but I still get some differentiation errors when using a `Flued.FixedResistances.Pipe` with more than one segment. Perhaps this should be investigate as part of the PR review? If not, I could create a separate issue for this.

**Code example to reproduce error**
```
model dynamicPipe_flow
  "Test of MSL mixture gas with Modelica Buildings components"
  package Medium = Modelica.Media.IdealGases.MixtureGases.FlueGasSixComponents;
  parameter Modelica.Units.SI.PressureDifference dp_nominal=1e4;
  parameter Modelica.Units.SI.MassFlowRate m_flow_nominal=10;

  Buildings.Fluid.FixedResistances.Pipe pip(
    redeclare package Medium = Medium,
    energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial,
    m_flow_nominal=m_flow_nominal,
    dp_nominal=dp_nominal,
    thicknessIns=0.1,
    lambdaIns=0.25,
    length=10)
    annotation (Placement(transformation(extent={{-10,-10},{10,10}})));
  Buildings.Fluid.Sources.Boundary_pT boundary(
    redeclare package Medium = Medium,
    T=1073.15,
    nPorts=1)
    annotation (Placement(transformation(extent={{-100,-10},{-80,10}})));
  Buildings.Fluid.Sources.MassFlowSource_T boundary1(
    redeclare package Medium = Medium,
    m_flow=-m_flow_nominal,
    nPorts=1) annotation (Placement(transformation(extent={{100,-10},{80,10}})));
equation 
  connect(boundary.ports[1], pip.port_a)
    annotation (Line(points={{-80,0},{-10,0}}, color={0,127,255}));
  connect(pip.port_b, boundary1.ports[1])
    annotation (Line(points={{10,0},{80,0}}, color={0,127,255}));
  annotation (uses(Modelica(version="4.0.0"), Buildings(version="10.0.0")),
      experiment(StopTime=60, __Dymola_Algorithm="Dassl"));
end dynamicPipe_flow;
```

**Comment by mwetter** [comment]
@justnielsen : Thanks for reporting. I will need to look at it most likely next week once the American Modelica Conference is over.

**Comment by mwetter** [comment]
The model `dynamicPipe_flow` does not translate because the differentiation of the medium fails:
```
The DAE has 1665 scalar unknowns and 1665 scalar equations.

Failed to differentiate the equation
pip.vol[9].dynBal.m = pip.vol[9].dynBal.fluidVolume*Modelica.Media.IdealGases.MixtureGases.FlueGasSixComponents.density_Unique14 (
Modelica.Media.IdealGases.Common.MixtureGasNasa.ThermodynamicState(
p = pip.vol[9].dynBal.medium.p, 
T = smooth(2, Modelica.Media.IdealGases.MixtureGases.FlueGasSixComponents.T_hX_Unique9 (pip.vol[9].dynBal.hOut, {0.768, 0.0, 0.0, 0.232, 0.0, 0.0}, true, Modelica.Media.Interfaces.Choices.ReferenceEnthalpy.ZeroAt0K, 0.0)), 
X = {0.768, 0.0, 0.0, 0.232, 0.0, 0.0}
));
```
I don't think there is anything we can do on the library side to make this model translate as the medium is from the Modelica Standard Library.

@MassimoCimmino : Can you please review this pull request so we can close the issue.

**Comment by MassimoCimmino** [comment]
@mwetter I will review this on Friday.

**Review by MassimoCimmino — APPROVED** [review]
This can be merged once tests have completed.

**Comment by mwetter** [comment]
@MassimoCimmino : Thanks, I will merge it when the tests pass

**Comment by justnielsen** [comment]
Hi @mwetter,

Although this issue has been closed a while ago I still get differentiation errors with the `dynamicPipe_flow` model above. Is there any chance that you could look into the issue again? To me it's unclear whether the differentiation error should be fixed in MSL or in IBPSA.

Background: I would like to use MSL medium models with IBPSA components, e.g. for modeling the flue gas path of a gas boiler.

Thanks

**Comment by mwetter** [comment]
@justnielsen : It turns out that if you set the constant
```modelica
Buildings.Fluid.FixedResistances.Pipe pip(
    vol(each simplify_mWat_flow=false),
...
```
then the model translates. This was tested with dymola 2024x and the following modified model:
```modelica
model dynamicPipe_flow
  "Test of MSL mixture gas with Modelica Buildings components"
  package Medium = Modelica.Media.IdealGases.MixtureGases.FlueGasSixComponents;
  parameter Modelica.Units.SI.PressureDifference dp_nominal=1e4;
  parameter Modelica.Units.SI.MassFlowRate m_flow_nominal=10;

  Buildings.Fluid.FixedResistances.Pipe pip(
    vol(each simplify_mWat_flow=false),
    redeclare package Medium = Medium,
    energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial,
    m_flow_nominal=m_flow_nominal,
    dp_nominal=dp_nominal,
    thicknessIns=0.1,
    lambdaIns=0.25,
    length=10)
    annotation (Placement(transformation(extent={{-10,-10},{10,10}})));
  Buildings.Fluid.Sources.Boundary_pT boundary(
    redeclare package Medium = Medium,
    T=1073.15,
    nPorts=1)
    annotation (Placement(transformation(extent={{-100,-10},{-80,10}})));
  Buildings.Fluid.Sources.MassFlowSource_T boundary1(
    redeclare package Medium = Medium,
    m_flow=-m_flow_nominal,
    nPorts=1) annotation (Placement(transformation(extent={{100,-10},{80,10}})));
equation 
  connect(boundary.ports[1], pip.port_a)
    annotation (Line(points={{-80,0},{-10,0}}, color={0,127,255}));
  connect(pip.port_b, boundary1.ports[1])
    annotation (Line(points={{10,0},{80,0}}, color={0,127,255}));
  annotation (uses(Modelica(version="4.0.0"), Buildings(version="10.0.0")),
      experiment(StopTime=60, __Dymola_Algorithm="Dassl"));
end dynamicPipe_flow;
```

**Comment by justnielsen** [comment]
@mwetter Thanks a lot for helping me out! This seemed to do the trick in the dynamic components that I'm currently using together with MSL media.

**Pull request merged**
