### PR TITLE
Issue725 flow functions

### LINKED ISSUE #725: reformulation of basicFlowFunctions
Similar to #723 `IBPSA.Fluid.BaseClasses.FlowModels.basicFlowFunction_dp` can be reformulated from 

```
   m_flow := if noEvent(dp>dp_turbulent) then k*sqrt(abs(dp))
           elseif noEvent(dp<-dp_turbulent) then -k*sqrt(abs(-dp))
         else (k^2*5/4/m_flow_turbulent)*dp-k/4/(m_flow_turbulent/k)^5*dp^3;
```

into 

```
     m_flow := if noEvent(abs(dp)>dp_turbulent)
               then sign(dp)*k*sqrt(abs(dp))
               else dp*m_flow_turbulent/dp_turbulent/4*(5-(dp/dp_turbulent)^2);
```

In a (best case) example model this yields a significant speedup. Consider the example:

```
model test
  parameter Integer i = 10000000;
  Real y;
algorithm 
  y:=0;
  for k in 1:i loop
    y :=y*IBPSA.Fluid.BaseClasses.FlowModels.basicFlowFunction_dp(
      0,
      0.5,
      2+time/1e10);
  end for;
end test;
```
which evaluates the function only in the regularisation region. I simulated this using
```
simulateModel("test", numberOfIntervals=1, method="Euler", fixedstepsize=1, resultFile="test");
```

The old formulation leads to:
```
Integration terminated successfully at T = 1
   CPU-time for integration      : 2.23 seconds
   CPU-time for one GRID interval: 2.23e+03 milli-seconds
...

Profiling information for the blocks.
Estimated overhead per call        0.00[us] total        0.000[s]
the estimated overhead has been subtracted below.
Name of block   , Block, Total CPU[s], Mean[us]    ( Min[us]    to Max[us]    ),   Called
Entire model    :     0,        0.000,        1.00 (       1.00 to        1.00),        3
Event handling  :     1,        2.520,  1260041.50 ( 1215051.00 to  1305032.00),        2
Empty timer     :     2,        0.000,        0.12 (       0.00 to        1.00),        8
Outside of model:     3,        0.000,       75.20 (       1.00 to      248.00),        5
AcceptedSection2:     4,        5.921,  1184230.00 ( 1086584.00 to  1305031.00),        5
 Auxiliary2 code:     5,        5.921,  1184229.00 ( 1086583.00 to  1305030.00),
```

The new formulations leads to:
```
(One-step solver with fixed stepsize and order 1)
Integration terminated successfully at T = 1
   CPU-time for integration      : 0.318 seconds
   CPU-time for one GRID interval: 318 milli-seconds
...
Profiling information for the blocks.
Estimated overhead per call        0.00[us] total        0.000[s]
the estimated overhead has been subtracted below.
Name of block   , Block, Total CPU[s], Mean[us]    ( Min[us]    to Max[us]    ),   Called
Entire model    :     0,        0.000,        1.00 (       1.00 to        1.00),        3
Event handling  :     1,        0.288,   143859.00 (  142819.00 to   144899.00),        2
Empty timer     :     2,        0.000,        0.12 (       0.00 to        1.00),        8
Outside of model:     3,        0.000,       34.00 (       1.00 to      100.00),        3
AcceptedSection2:     4,        0.743,   148631.20 (  137263.00 to   180118.00),        5
 Auxiliary2 code:     5,        0.743,   148630.00 (  137262.00 to   180117.00),        5
```

the cpu times seem to be self-inconsistent but they do show a clear advantage of the new formulation. Re-adding the `else if` construct does not affect computation time so the gains in computation time seem to be entirely related to the formulation of the `else` branch.  

When changing the else branch from
`dp*m_flow_turbulent/dp_turbulent/4*(5-(dp/dp_turbulent)^2)` to
`dp*m_flow_turbulent^5/m_flow_turbulent^4/dp_turbulent/4*(5-(dp/dp_turbulent)^2)`
computation time rises by more than a factor of 10.

`(m_flow_turbulent/k)^2` is a lot faster than `(m_flow_turbulent/k)*(m_flow_turbulent/k)`.

Adding and eliminating
`  Modelica.SIunits.PressureDifference dp_div = dp/dp_turbulent
    "Help variable for computational efficiency";`

Leads to `CPU-time for integration      : 0.255 seconds`

Replacing `/4` by `*0.25` does not have a noticeable effect.

I'm not sure what's going on, but I suggest to go with this new formulation:
```
      m_flow := if noEvent(abs(dp)>dp_turbulent)
                then sign(dp)*k*sqrt(abs(dp))
                else 0.25*dp_div*m_flow_turbulent*(5-dp_div^2);
```

### PR DESCRIPTION
**Pull request by Mathadon**
this closes #725

### CODE REVIEW

**Comment by Mathadon** [comment]
travis fails:

```
*** Warning: To_VolumeFraction.mat: conVolFlo.y has absolute and relative error = 2.623e-03, 1.203e-04.
             Maximum error is at t = 12960.0
```
I compared the results manually in Dymola:

screen shot 2017-04-14 at 12 34 40

the relative error is a bit larger than 1e-4.

Setting  `from_dp=true` in the `PressureDrop` avoids the need for an algebraic loop that solved for the flow rate and removes the error. The error then becomes zero. Do we change the model to use `from_dp = true` to avoid future problems?
This example clearly shows that the solver tolerance of 1e-6 is not obtained, so we may need to relax the tolerance further in Buildingspy to avoid problems in the future?

**Comment by Mathadon** [comment]
#743 should be merged first

**Comment by Mathadon** [comment]
@mwetter travis is returning `Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password` and I'm not sure why?

**Comment by mwetter** [comment]
I restarted the job, let's see if it goes away.

**Comment by Mathadon** [comment]
nope :(

**Comment by thorade** [comment]
Can you locally merge the master into this branch and then push it? Travis says: "github comitted..." when using the "Update branch" button in the PR web interface. Just guessing, though

**Comment by Mathadon** [comment]
the branch was already up to date so I added a dummy commit

**Comment by thorade** [comment]
That is strange, because github shows me the message: branch is out-of-date with the base branch! And next to it, the update button.

**Comment by thorade** [comment]
One more strange thing: I just clicked Edit in the top right corner and changed the base to "master". Maybe the PR was created before the latest renaming?

**Comment by Mathadon** [comment]
it does so for me too..

**Comment by thorade** [comment]
Still fails

**Comment by mwetter** [comment]
The checks work for me locally, so I will merge it.

**Pull request merged**
