### PR TITLE
propagate flowReversal in masFloDiv and masFloMul of PartialBorefield.mo

### LINKED ISSUE #1329: allowFlowReversal not correctly propagated in PartialBorefield
the parameter `allowFlowReversal` of the components `masFloDiv` and `masFloMul` of `IBPSA.Fluid.Geothermal.Borefields.BaseClasses.PartialBorefield` are not propagated. I will make a pull request.

### PR DESCRIPTION
**Pull request by damienpicard**
this closes #1329

### CODE REVIEW

**Comment by Mathadon** [comment]
@damienpicard any chance to have this PR without rewriting the whole file?

**Comment by mwetter** [comment]
@damienpicard : Can you please address the comment https://github.com/ibpsa/modelica-ibpsa/pull/1330#issuecomment-607958424 so we can finish this. Thanks.

**Comment by damienpicard** [comment]
@Mathadon and @mwetter not sure what went wrong. My Tortoise Git diff showed no file overwrite but git bash did. I re-did the changes with a text editor and it seems to work now.

Sorry for the mesh.

**Comment by Mathadon** [comment]
@mwetter this is ready for review

**Pull request merged**
