### PR TITLE
Issue1205 boundary

### LINKED ISSUE #1205: Fluid boundaries not working with ideal gas mixtures
This is to correct the issue reported by @justnielsen through https://github.com/lbl-srg/modelica-buildings/issues/1543

------------------
I am trying to use Modelica Buildings with MSL mixture gasses. 

In the simples possible case I connect a mass flow source to a pressure sink and use `Modelica.Media.IdealGases.MixtureGases.FlueGasSixComponents`. 

```
model SourceToSink
  package Medium = Modelica.Media.IdealGases.MixtureGases.FlueGasSixComponents;
  Buildings.Fluid.Sources.MassFlowSource_T boundary(redeclare package Medium = Medium, nPorts=1);
  Buildings.Fluid.Sources.Boundary_pT bou(redeclare package Medium = Medium, nPorts=1);
equation 
  connect(boundary.ports[1], bou.ports[1]);
end SourceToSink;
```

This gives a model with 26 equations and 25 unknowns.

Looking into `Buildings.Fluid.Sources.BaseClasses.PartialSource_Xi_C.mo`, I see some problems around the lines

```
if not use_X_in then
  X_in_internal[1:Medium.nXi] = Xi_in_internal[1:Medium.nXi];
  X_in_internal[Medium.nX] = 1-sum(X_in_internal[1:Medium.nXi]);
end if;
```

Since I have chosen not to use an external mass fraction input, I would expect a connection between `X_in_internal` and `X`. If I replace the two lines in the if statement with
`X_in_internal = X` (like in the Modelica.Fluid.Sources) the model works.

Also, if I specify the `X` as an internal input vector in the simple model above, it fails to work.

### PR DESCRIPTION
**Pull request by mwetter**
This closes #1205

### CODE REVIEW

**Comment by mwetter** [comment]
@Mathadon : There are still a few examples that fail:
```
*** Error: Model check failed for 'IBPSA.Fluid.FixedResistances.Validation.PlugFlowPipes.TransportWaterAir'.
*** Error: Simulation failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FixedResistances/Validation/PlugFlowPipes/TransportWaterAir.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Validation.FMUs.ThermalZoneAir2'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Validation/FMUs/ThermalZoneAir2.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Validation.FMUs.HVACThermalZoneAir2'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Validation/FMUs/HVACThermalZoneAir2.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Validation.FMUs.HVACThermalZoneAir3'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Validation/FMUs/HVACThermalZoneAir3.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.HeatExchangers.Examples.DryCoilEffectivenessNTUMassFlow'.
*** Error: Simulation failed for 'RunScript("Resources/Scripts/Dymola/Fluid/HeatExchangers/Examples/DryCoilEffectivenessNTUMassFlow.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Validation.FMUs.ThermalZoneAir1'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Validation/FMUs/ThermalZoneAir1.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Validation.FMUs.HVACThermalZoneAir1'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Validation/FMUs/HVACThermalZoneAir1.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Validation.FMUs.ThermalZoneAir3'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Validation/FMUs/ThermalZoneAir3.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.Adaptors.Examples.ThermalZoneHVACNoExhaust'.
*** Error: Simulation failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/Adaptors/Examples/ThermalZoneHVACNoExhaust.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.Adaptors.Examples.ThermalZoneHVACWithExhaust'.
*** Error: Simulation failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/Adaptors/Examples/ThermalZoneHVACWithExhaust.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Examples.FMUs.HVACZone'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Examples/FMUs/HVACZone.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Examples.FMUs.ThermalZone'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Examples/FMUs/ThermalZone.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Examples.FMUs.ThermalZones'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Examples/FMUs/ThermalZones.mos");'.
*** Error: Model check failed for 'IBPSA.Fluid.FMI.ExportContainers.Examples.FMUs.HVACZones'.
*** Error: FMU export failed for 'RunScript("Resources/Scripts/Dymola/Fluid/FMI/ExportContainers/Examples/FMUs/HVACZones.mos");'.
```
Can you please have a look at this implementation. It is not clear why `Resources/Scripts/Dymola/Fluid/FixedResistances/Validation/PlugFlowPipes/TransportWaterAir.mos` fails even if the district pipe is removed.

**Comment by mwetter** [comment]
@Mathadon : The tests that fail seem all to use `use_X_in` rather than `use_Xi_in`. 
Best is to make another test similar to `BoundaryWithXi_in` for this case. I should be able to do this next week.

**Comment by Mathadon** [comment]
Let's hope that 2ff074a solves it.

**Comment by mwetter** [comment]
@Mathadon This is ready to review and merge.

**Comment by mwetter** [comment]
@Mathadon : Is there anything that holds this up?

**Comment by Mathadon** [comment]
Oops, I missed the e-mail asking for a review.

**Pull request merged**
