### PR TITLE
New (and updated) Airflow Classes

### PR DESCRIPTION
**Pull request by kldjonge**
New components and related baseclasses were developed for modelling multizone airflow.

### CODE REVIEW

**Comment by MassimoCimmino** [comment]
@kldjonge Is the pull request up to date? As I mentioned on the last WP1.1 call, I can make a first review.

**Comment by kldjonge** [comment]
It is up-to-date. A first review would be great!

**Comment by MassimoCimmino** [comment]
@kldjonge I made a quick review of the commits on the pull request and annotated the code on [my fork](https://github.com/MassimoCimmino/modelica-ibpsa/tree/MAAirflowv2).

The "biggest" issues I find are the calls to spline interpolation in `IBPSA.Airflow.Multizone.BaseClasses.flowElementData` in and `IBPSA.Airflow.Multizone.BaseClasses.windPressureProfile`, and the missing test cases for the new models. I suggest to uniformize the naming of models and variables (e.g. `PowerLaw` vs `Powerlaw`, and `_MassFlow` vs `_mflow` vs `_m_flow`), and to update the user's guide (`IBPSA.Airflow.Multizone.UsersGuide`) as it will become out-of-date.

**Comment by kldjonge** [comment]
Many thanks for the review. Looks like it is mainly small changes and naming issues/inconsistencies.

Concerning the splines I will have to rethink the implementation a little then. I tried to **not** have the derivatives (and eg. the addition of the previous and last point) at top level for clarity/readability of the models. Any suggestions on how to implement it alternatively to avoid redoing the calculation of the derivatives every time step but stil not clutter the top-level model to much with these 'background' calculations?

**Comment by kldjonge** [comment]
@mwetter, does is not make sense to allow this merge into https://github.com/ibpsa/modelica-ibpsa/tree/issue1436_AirflowNewClasses already? 

For review purposes it seems more logical that eg. Massimo can edit in the same repository. Now, changes were made on his fork and I cherry picked them to mine to link it back to this pull request. If this is the typical way of working it no problem off course, just wondering if this is the most efficient workflow.

**Comment by MassimoCimmino** [comment]
I don't think the initialization of derivatives would clutter the `TableData_` models since the interpolation is the only operation at the top level.

**Comment by mwetter** [comment]
@kldjonge @MassimoCimmino : That's fine to merge into this development branch, which I will do now.

**Comment by kldjonge** [comment]
@MassimoCimmino , I incorporated your proposed fixes. I also updated some of the annotation and made some minor enhancements to some models along the way.

For the validation of the models, I made a CONTAM model as testdata for the one way flow elements and embedded the data:
[IBPSA_FlowElement_Data.xlsx](https://github.com/ibpsa/modelica-ibpsa/files/6267599/IBPSA_FlowElement_Data.xlsx)
At the actual datapoints, the data almost perfectly corresponds. In modelica, looking at the data, it looks like there might be a slight difference, but that is mainly due to the interpolation of the testdata.

**Comment by kldjonge** [comment]
@mwetter, shouldn't we move from my fork to the IBPSA development branch (MAAirflowv2) already to make the reviewing easier?

**Comment by mwetter** [comment]
> @mwetter, shouldn't we move from my fork to the IBPSA development branch (issue1436_AirflowNewClasses) already to make the reviewing easier?

Since @Mathadon will do the next review I will leave it up to him to merge on a development branch to avoid that I interfere with his revisions/edits.

**Comment by Mathadon** [comment]
👍

**Comment by kldjonge** [comment]
This PR is replaced by https://github.com/ibpsa/modelica-ibpsa/pull/1500

**Pull request closed without merging**
