### PR TITLE
Issue877 medium column

### PR DESCRIPTION
**Pull request by Mathadon**
see #877

### CODE REVIEW

**Comment by Mathadon** [comment]
@mwetter this is ready to be merged

**Comment by mwetter** [comment]
- [ ] In ``MediumColumn``, I suggest to remove ``use_constantPressureForDensity`` as I don't see why someone would set this to ``false``. E.g., I suggest you implement the behavior for ``use_constantPressureForDensity = true``.
- [ ] I don't see why someone would set ``p_default`` to a value different from ``Medium.p_default``. What else should it reasonably be? 

Hence, if we hardcode ``p_default=Medium.p_default`` and remove the option to set ``use_constantPressureForDensity=false``, the model would get simpler. The error will be small as 1E5/(1E5-500)=1.005, which is an extreme case. Usually, dp across rooms is a few Pascal only.


Note that

* ``IBPSA.Airflow.Multizone.MediumColumn`` removes the parameter ``allowFlowReversal``
* ``IBPSA.Airflow.Multizone.BaseClasses.PowerLawResistance`` sets ``final allowFlowReversal = true`` (which was not ``final`` before). This affects ``IBPSA.Airflow.Multizone.Orifice`` and ``IBPSA.Airflow.Multizone.EffectiveAirLeakageArea``.

These are non-backward compatible changes and need to be handled according to https://github.com/ibpsa/modelica-ibpsa/wiki/Workflow-for-code-changes#non-backward-compatible-changes

Can you add a snippet for the conversion script that the libraries can then add to their conversion scripts?

**Comment by Mathadon** [comment]
@mwetter I incorporated your suggestions.

The script should be:
```
convertModifiers("IBPSA.Airflow.Multizone.MediumColumn",{"use_constantPressureForDensity"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.MediumColumn",{"p_default"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.MediumColumnDynamic",{"use_constantPressureForDensity"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.MediumColumnDynamic",{"p_default"}, fill("",0), true);
``` 

Should I include this in a .mos file in the repo?

**Comment by mwetter** [comment]
@Mathadon The conversion script should be
```
convertModifiers("IBPSA.Airflow.Multizone.MediumColumnDynamic", {"allowFlowReversal"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.MediumColumn", {"allowFlowReversal"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.EffectiveAirLeakageArea", {"allowFlowReversal"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.Orifice", {"allowFlowReversal"}, fill("",0), true);
```
as it needs to list the parameter values that changed. The ones that you listed were never part of a model other than during the development on this branch.

@thorade @mlauster Can you please approve this pull request if you agree with the changes, as this is a backward incompatible change.

**Comment by Mathadon** [comment]
@mwetter I think this can be merged?

**Comment by mwetter** [comment]
This is ready to be merged if the tests pass.

**Pull request merged**
