### PR TITLE
Modifications for #842

### PR DESCRIPTION
**Pull request by AnaConstantin**
1. Added function to evaluate the time span of the weather data getTimeSpanWeatherData.mo.
2. Modified ReaderTMY3.mo to evaluate the time span and decide if the convert time block should be used or not.
3. Some minor modifications:
- changed longitude to latitude for error message in getLatitudeTMY3.mo
- added table name as parameter for ReaderTMY3.mo, in order not to have it hidden inside the model and address a more general approach to tables.

If review is passed, I can also update the documentation and the revision section of ReaderTMY3.mo

### CODE REVIEW

**Comment by thorade** [comment]
I'll merge this as it is, so that the code is in the IBPSA repository, so that the tests can be run on it.
If you have more changes, you can just keep committing to your branch, and then open a new pull request from your issue branch into the IBPSA issue branch.

**Comment by thorade** [comment]
See test results for branches here:
https://travis-ci.org/ibpsa/modelica-ibpsa/branches

**Comment by thorade** [comment]
@AnaConstantin Could you have a look at why the tests are failing and try to fix it?

**Comment by AnaConstantin** [comment]
Tried to fix them via #857.

**Comment by thorade** [comment]
Thanks, the code will now be tested by Travis.
One very minor note: If you add the issue number #842 in the **text** of the pull request (instead of in the title) then github will generate nicer cross-references.

**Comment by AnaConstantin** [comment]
Thanks for the tip. I was not aware of the fact that it does not link to the issue if the reference is in the title.
I'll check in one hour to see if the tests ran correctly this time.

**Comment by thorade** [comment]
The only failure now is due to missing reference results for the new test.
Reference results (currently) have to be generated with BuildingsPY on Ubuntu 16.04 with Dymola 2017FD01. Do you know how to do that?

**Comment by AnaConstantin** [comment]
Short answer: No, I do not know how to do it and have no access to a Linux machine. 
Long answer: you sure we need to do it? I suppose the example will be deleted if my (or another) solution is considered correct, since this is more of a bug issue, than an extend functionality issue, for which a new permanent example would make sense.

**Pull request merged**
