### PR TITLE
Issue271 linear damper

### PR DESCRIPTION
**Pull request by dhblum**
The Linear damper was implemented in an analogous way to Valves.TwoWayPressureIndependent.

A remaining question is if/how the underlying implementation of the linear damper and pressure independent valve should be encapsulated in a base class, from which the two could extend to prevent repeat code.

### CODE REVIEW

**Comment by mwetter** [comment]
@Mathadon Can you please merge if you are OK with the changes.

**Comment by Mathadon** [comment]
@dhblum once we get #156 merged to the master I can merge the master back into this branch and update the code, okay?

**Comment by dhblum** [comment]
Sounds good to me, thanks!

**Comment by mwetter** [comment]
@Mathadon : Since #156  is now on the master, can you please merge the master into this branch and resolve the conflict that arose due to the pressure independent valve and pressure independent damper. (This will be needed to merge the latest changes to Buildings which already has this damper.)

**Comment by Mathadon** [comment]
I'll check it tomorrow!

**Comment by Mathadon** [comment]
I merged master and changed the default values of `deltax` since they lead to relatively large 'errors' and a relatively wide regularisation region. I hope that's ok.

**Comment by Mathadon** [comment]
@mwetter this fails also when restarted by @dhblum 
We could close the pull request and make a new one?

**Comment by mwetter** [comment]
@Mathadon : I will close this PR and open a new one, maybe this helps.

**Pull request closed without merging**
