### PR TITLE
Included ModelicaAllocateString.h in cryptographicsHash.c

### PR DESCRIPTION
**Pull request by mwetter**
This integrates https://github.com/lbl-srg/modelica-buildings/pull/2784
It avoids a wrong memory access in OpenModelica

### CODE REVIEW

**Comment by Mathadon** [comment]
Interesting fix.. 

In https://github.com/open-ideas/IDEAS/issues/1225#issuecomment-884737144 we had a case where we had to remove `ModelicaUtilities.h` to fix a bug, and here it should be added. See also this related post by @casella : https://github.com/open-ideas/IDEAS/issues/1225#issuecomment-885588542 

I'm ok with merging this but there may be an underlying problem that may need to be looked into to avoid similar problems in the future with OM.

**Comment by casella** [comment]
Wait, see discussion [here](https://github.com/lbl-srg/modelica-buildings/pull/2784)

**Comment by Mathadon** [comment]
Happy to proceed with this after the feedback from @casella here: https://github.com/lbl-srg/modelica-buildings/pull/2784#issuecomment-979414713 !

**Comment by casella** [comment]
> Happy to proceed with this after the feedback from @casella here: [lbl-srg/modelica-buildings#2784 (comment)](https://github.com/lbl-srg/modelica-buildings/pull/2784#issuecomment-979414713) ! This can be merged.

@Mathadon, you need to explicitly post a positive review to allow merging in, I guess. GitHub is not smart enough to read between the lines of your comment 😄

**Comment by casella** [comment]
BTW, the fix worked fine in Buildings, see [report](https://libraries.openmodelica.org/branches/history/master/2021-11-25%2011:41:34..2021-11-25%2015:40:12.html).

**Review by Mathadon — APPROVED** [review]

**Comment by Mathadon** [comment]
@casella Fair point, I guess that I got used to @mwetter using his admin privileges 😅

**Pull request merged**
