### PR TITLE
Issue789 wilo ip e 50/150 4/2 data

### PR DESCRIPTION
**Pull request by thorade**
@icupeiro and @mathadon
this replaces #790 
if necessary, you can add more commits to your branch in you fork and someone will merge them into the issue branch here in the ibpsa repo

### CODE REVIEW

**Comment by Mathadon** [comment]
@thorade thank you :)

**Comment by thorade** [comment]
@Mathadon you are welcome. The tests pass and you have reviewed it once in the past. Do you want to merge it?

**Comment by Mathadon** [comment]
I checked the code and to me it looks good. I'm not sure if @mwetter wants to review it?

**Comment by mwetter** [comment]
This is ready to merge when all tests pass.

**Pull request merged**
