### PR TITLE
Issue1645 fan efficiency euler patch

### PR DESCRIPTION
**Pull request by Mathadon**
@mwetter can this be merged? See https://github.com/ibpsa/modelica-ibpsa/pull/1646#issuecomment-1320920539

### CODE REVIEW

**Comment by Mathadon** [comment]
@mwetter see also [327621a](https://github.com/ibpsa/modelica-ibpsa/pull/1665/commits/327621ab13bf2513e33329bb69a8068bda249d23) 
shouldn't this have been caught by tidylib?

**Comment by mwetter** [comment]
@Mathadon Please go ahead and merge it, but I assume you then will actually used the 500x faster approximation in the model?
Note that `smoothOrder` should be added, and 
```a*x^3+b*x^2+c*x+d``` is likely faster as
```d+x*(c+x*(b+x*a))``` (at least in C).

Regarding tidylib, I would think this should be caught, but I think it is not 100% foolproof.

**Comment by Mathadon** [comment]
@hcasperfu @mwetter Since I'm not very familiar with the new code, are you able to help out with the integration of the new function? Otherwise no problem and I'll have a go at it!

**Comment by mwetter** [comment]
@Mathadon : @hcasperfu should be able to help, but he is currently out of the office.

**Pull request merged**
