### PR TITLE
Removed parameter CD

### LINKED ISSUE #932: Airflow.Multizone.EffectiveAirLeakageArea has non-used parameter
This issue is to remove the parameter `CD` from `Airflow.Multizone.EffectiveAirLeakageArea` as it is not used in the model. This requires using `BaseClasses.PowerLawResistance` rather than `Orifice` as the base class.

### PR DESCRIPTION
**Pull request by mwetter**
This closes #932

### CODE REVIEW

**Comment by mwetter** [comment]
The non-backward compatible changes are the removal of parameters `A` and `CD` in 
`IBPSA.Airflow.Multizone.EffectiveAirLeakageArea`.
Also, the assignment `v = V_flow/A` has been removed from `IBPSA/Airflow/Multizone/BaseClasses/PowerLawResistance.mo` and need to be provided by the class that extend from this partial class.

The entry for the conversion script is
```
convertModifiers("IBPSA.Airflow.Multizone.EffectiveAirLeakageArea",
                 {"A", "CD"}, fill("",0), true);
```

**Comment by mwetter** [comment]
@Mathadon @mlauster @nytschgeusen Can you please indicate if this non-backward compatible change is OK for your libraries.

**Comment by Mathadon** [comment]
@mwetter if we are making this backward-incompatible change then I propose to also remove `forceErrorControlOnFlow`. We may also want to move some of the less important parameters out of the main tab, i.e. `lWet`, `useDefaultProperties` and `dp_turbulent`.

**Comment by Mathadon** [comment]
Furthermore, `IBPSA.Airflow.Multizone.BaseClasses.PowerLawResistance` defines `allowFlowReversal` but does not use it in 

```
  // Isenthalpic state transformation (no storage and no loss of energy)
  port_a.h_outflow = inStream(port_b.h_outflow);
  port_b.h_outflow = inStream(port_a.h_outflow);

  // Mass balance (no storage)
  port_a.m_flow + port_b.m_flow = 0;

  // Transport of substances
  port_a.Xi_outflow = inStream(port_b.Xi_outflow);
  port_b.Xi_outflow = inStream(port_a.Xi_outflow);

  port_a.C_outflow = inStream(port_b.C_outflow);
  port_b.C_outflow = inStream(port_a.C_outflow);
```

**Comment by mlauster** [comment]
Apart from @Mathadon remarks, Aachen is fine. :-)

**Comment by Mathadon** [comment]
For some analysis on `forceErrorControlOnFlow` see https://github.com/ibpsa/modelica-ibpsa/commit/de008b7de1e88a100784d890fc4dfebfa6f0f7b0#commitcomment-29447735 . 
For me the fix is to not model compressible flow, rather than using `forceErrorControlOnFlow`.

**Comment by mwetter** [comment]
I moved `useDefaultProperties` and `dp_turbulent` to the `Advanced` tab.
I removed the note about `CD` being removed in future releases.

I also removed `lWet` and `Re`.

The complete entry for the conversion script should be
```
convertModifiers("IBPSA.Airflow.Multizone.EffectiveAirLeakageArea",
                 {"A", "CD", "lWet"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.Orifice", {"lWet"}, fill("",0), true);
```
@Mathadon : Please let me know if this is ready to be merged.

**Comment by Mathadon** [comment]
@mwetter looks good, thanks!

**Pull request merged**
