### PR TITLE
Issue1019 if smooth transition

### PR DESCRIPTION
**Pull request by dhblum**
Changes if-statement to if-expression.

### CODE REVIEW

**Comment by thorade** [comment]
Do you know `sign(x)` ?
I think it should work here, too. Not sure whether it generates events.

**Comment by Mathadon** [comment]
Better check first whether `sign(x)` is supported by JModelica.

**Comment by thorade** [comment]
I just tested it and it is supported. Also, it is specified in the language specification.

**Comment by dhblum** [comment]
casADi doesn't seem to like the use of sign, I get the following error when I change the implementation to:

` y := sign(x) * (a + aX*(b + aX*(c + aX*(d + aX*(e + aX*f)))));`

```
Java error occurred: 
Exception in thread "main" java.lang.UnsupportedOperationException: Cannot convert expression to MX: sign(x)
```

**Pull request merged**
