### PR TITLE
Issue722 q lat flow

### LINKED ISSUE #722: {Two, Four}PortHeatMassExchanger have wrong Q_flow if latent heat is exchanged
This merges the changes from
https://github.com/lbl-srg/modelica-buildings/issues/704

See the documentation of the above tickets for the bug fix.

### PR DESCRIPTION
**Pull request by mwetter**
This closes #722.

See https://github.com/lbl-srg/modelica-buildings/issues/704 for a discussion.

This is not backwards compatible because the input connector `TWat` of the `MixingVolumeMoistAir` has been removed. Also, the `heatPort` should be assigned the total heat flow rate, not just the sensible (the comment of the port and the info section has been updated).

As this is a non-backward compatible change, @mlauster , @Mathadon and @thorade (or someone from their team) should indicate that it is OK to merge within two weeks.

### CODE REVIEW

**Comment by mlauster** [comment]
Fine for Aachen

**Comment by Mathadon** [comment]
Ok for Leuven

**Comment by mwetter** [comment]
@thorade Are you fine with this change or do you need more time to review?

**Comment by thorade** [comment]
Fine for me, too

Am 26.04.2017 6:47 nachm. schrieb "Michael Wetter" <notifications@github.com

**Pull request merged**
